name:                haskalytic
version:             0.1.0.0
github:              "PaulJohnson/haskalytic"
license:             BSD3
author:              "Paul Johnson"
maintainer:          "paul@cogito.org.uk"
copyright:           "Ⓒ 2022 Paul Johnson"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/haskalytic#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  default-extensions:
  - TupleSections
  dependencies:
  - algebraic-graphs
  - containers
  - hiedb
  - lens

executables:
  haskalytic:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - algebraic-graphs
    - ansi-terminal
    - containers
    - directory
    - haskalytic
    - hiedb
    - optparse-applicative
  haskalytic-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - algebraic-graphs
    - ansi-terminal
    - containers
    - directory
    - haskalytic
    - hiedb
    - optparse-applicative

tests:
  haskalytic-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskalytic
